### ISSUE TITLE
votekick sometimes doesn't increment the counter

### ISSUE THREAD

**Issue by RiedleroD** [RiedleroD/dev_meme_bot#8]
idfk

![image](https://github.com/RiedleroD/dev_meme_bot/assets/57227431/081ab219-3468-451e-950a-2106bcf68c33)
![image](https://github.com/RiedleroD/dev_meme_bot/assets/57227431/38af594b-aec9-4cf7-abeb-a743be860213)

**Comment by purplesyringa** [comment]
Fixed. The remote database had a wrong `primary key` constraint.

**Comment by RiedleroD** [comment]
I want to die. And I'm taking SQL with me.
